---
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Password for Basic-Auth at the password management endpoints."
  shortDescription: "Password for Basic-Auth at the password management endpoints."
  name: "cas.authn.pm.rest.endpoint-password"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Endpoint URL to use when updating passwords.."
  shortDescription: "Endpoint URL to use when updating passwords.."
  name: "cas.authn.pm.rest.endpoint-url-change"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Endpoint URL to use when locating email addresses."
  shortDescription: "Endpoint URL to use when locating email addresses."
  name: "cas.authn.pm.rest.endpoint-url-email"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Endpoint URL to use when locating phone numbers."
  shortDescription: "Endpoint URL to use when locating phone numbers."
  name: "cas.authn.pm.rest.endpoint-url-phone"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Endpoint URL to use when locating security questions."
  shortDescription: "Endpoint URL to use when locating security questions."
  name: "cas.authn.pm.rest.endpoint-url-security-questions"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Endpoint URL to use when locating user names."
  shortDescription: "Endpoint URL to use when locating user names."
  name: "cas.authn.pm.rest.endpoint-url-user"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm-rest"
  owner: "org.apereo.cas.configuration.model.support.pm.RestfulPasswordManagementProperties"
  type: "java.lang.String"
  description: "Username for Basic-Auth at the password management endpoints."
  shortDescription: "Username for Basic-Auth at the password management endpoints."
  name: "cas.authn.pm.rest.endpoint-username"
  defaultValue: ""
