---
- required: true
  module: "cas-server-support-shiro-authentication"
  owner: "org.apereo.cas.configuration.model.support.generic.ShiroAuthenticationProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.authn.shiro.location"
  defaultValue: ""
- module: "cas-server-support-shiro-authentication"
  owner: "org.apereo.cas.configuration.model.support.generic.ShiroAuthenticationProperties"
  type: "java.lang.String"
  description: "Name of the authentication handler."
  shortDescription: "Name of the authentication handler."
  name: "cas.authn.shiro.name"
  defaultValue: ""
- module: "cas-server-support-shiro-authentication"
  owner: "org.apereo.cas.configuration.model.support.generic.ShiroAuthenticationProperties"
  type: "java.util.Set<java.lang.String>"
  description: "Required permissions that should be authorized by Shiro."
  shortDescription: "Required permissions that should be authorized by Shiro."
  name: "cas.authn.shiro.required-permissions"
  defaultValue: ""
- module: "cas-server-support-shiro-authentication"
  owner: "org.apereo.cas.configuration.model.support.generic.ShiroAuthenticationProperties"
  type: "java.util.Set<java.lang.String>"
  description: "Required roles that should be authorized by Shiro."
  shortDescription: "Required roles that should be authorized by Shiro."
  name: "cas.authn.shiro.required-roles"
  defaultValue: ""
