---
- required: true
  module: "cas-server-support-pm"
  owner: "org.apereo.cas.configuration.model.support.pm.GroovyPasswordManagementProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.authn.pm.groovy.location"
  defaultValue: ""
- required: true
  module: "cas-server-support-pm"
  owner: "org.apereo.cas.configuration.model.support.pm.JsonPasswordManagementProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.authn.pm.json.location"
  defaultValue: ""
