---
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Use a local cache to reduce fetches.."
  shortDescription: "Use a local cache to reduce fetches.."
  name: "cas.authn.saml-idp.metadata.couch-db.caching"
  defaultValue: false
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Remove idle connections from pool."
  shortDescription: "Remove idle connections from pool."
  name: "cas.authn.saml-idp.metadata.couch-db.cleanup-idle-connections"
  defaultValue: true
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "TCP connection timeout."
  shortDescription: "TCP connection timeout."
  name: "cas.authn.saml-idp.metadata.couch-db.connection-timeout"
  defaultValue: 1000
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Create the database if it doesn't exist."
  shortDescription: "Create the database if it doesn't exist."
  name: "cas.authn.saml-idp.metadata.couch-db.create-if-not-exists"
  defaultValue: true
- required: true
  module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.String"
  description: "Database name."
  shortDescription: "Database name."
  name: "cas.authn.saml-idp.metadata.couch-db.db-name"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Use TLS. Only needed if not specified by URL."
  shortDescription: "Use TLS."
  name: "cas.authn.saml-idp.metadata.couch-db.enable-ssl"
  defaultValue: false
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Whether identity provider metadata artifacts are expected to be found\
    \ in the database."
  shortDescription: "Whether identity provider metadata artifacts are expected to\
    \ be found in the database."
  name: "cas.authn.saml-idp.metadata.couch-db.idp-metadata-enabled"
  defaultValue: false
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Max entries in local cache."
  shortDescription: "Max entries in local cache."
  name: "cas.authn.saml-idp.metadata.couch-db.max-cache-entries"
  defaultValue: 1000
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Maximum connections to CouchDB."
  shortDescription: "Maximum connections to CouchDB."
  name: "cas.authn.saml-idp.metadata.couch-db.max-connections"
  defaultValue: 20
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Largest allowable serialized object."
  shortDescription: "Largest allowable serialized object."
  name: "cas.authn.saml-idp.metadata.couch-db.max-object-size-bytes"
  defaultValue: 8192
- required: true
  module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.String"
  description: "Password for connection."
  shortDescription: "Password for connection."
  name: "cas.authn.saml-idp.metadata.couch-db.password"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.String"
  description: "Proxy host."
  shortDescription: "Proxy host."
  name: "cas.authn.saml-idp.metadata.couch-db.proxy-host"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "proxy port."
  shortDescription: "proxy port."
  name: "cas.authn.saml-idp.metadata.couch-db.proxy-port"
  defaultValue: -1
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Relax TLS settings–like certificate verification."
  shortDescription: "Relax TLS settings–like certificate verification."
  name: "cas.authn.saml-idp.metadata.couch-db.relaxed-ssl-settings"
  defaultValue: false
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Retries for update conflicts."
  shortDescription: "Retries for update conflicts."
  name: "cas.authn.saml-idp.metadata.couch-db.retries"
  defaultValue: 5
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Socket idle timeout."
  shortDescription: "Socket idle timeout."
  name: "cas.authn.saml-idp.metadata.couch-db.socket-timeout"
  defaultValue: 10000
- required: true
  module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.String"
  description: "Connection url."
  shortDescription: "Connection url."
  name: "cas.authn.saml-idp.metadata.couch-db.url"
  defaultValue: "http://localhost:5984"
- module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Expect HTTP 100 Continue during connection."
  shortDescription: "Expect HTTP 100 Continue during connection."
  name: "cas.authn.saml-idp.metadata.couch-db.use-expect-continue"
  defaultValue: true
- required: true
  module: "cas-server-support-saml-idp-metadata-couchdb"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.CouchDbSamlMetadataProperties"
  type: "java.lang.String"
  description: "Username for connection."
  shortDescription: "Username for connection."
  name: "cas.authn.saml-idp.metadata.couch-db.username"
  defaultValue: ""
