---
- module: "cas-server-support-throttle-bucket4j"
  owner: "org.apereo.cas.configuration.model.support.throttle.Bucket4jThrottleProperties"
  type: "java.lang.Boolean"
  description: "Whether the request should block until capacity becomes available."
  shortDescription: "Whether the request should block until capacity becomes available."
  name: "cas.authn.throttle.bucket4j.blocking"
  defaultValue: true
- module: "cas-server-support-throttle-bucket4j"
  owner: "org.apereo.cas.configuration.model.support.throttle.Bucket4jThrottleProperties"
  type: "java.lang.Integer"
  description: "Number of tokens that can be used within the time window."
  shortDescription: "Number of tokens that can be used within the time window."
  name: "cas.authn.throttle.bucket4j.capacity"
  defaultValue: 120
- module: "cas-server-support-throttle-bucket4j"
  owner: "org.apereo.cas.configuration.model.support.throttle.Bucket4jThrottleProperties"
  type: "java.lang.Integer"
  description: "Indicate the overdraft used if requests are above the average capacity.\
    \ A positive value activates a greedy strategy for producing tokens for capacity."
  shortDescription: "Indicate the overdraft used if requests are above the average\
    \ capacity."
  name: "cas.authn.throttle.bucket4j.overdraft"
  defaultValue: 0
- module: "cas-server-support-throttle-bucket4j"
  owner: "org.apereo.cas.configuration.model.support.throttle.Bucket4jThrottleProperties"
  type: "java.lang.Integer"
  description: "Time window in which capacity can be allowed."
  shortDescription: "Time window in which capacity can be allowed."
  name: "cas.authn.throttle.bucket4j.range-in-seconds"
  defaultValue: 60
