---
- duration: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Client execution timeout."
  shortDescription: "Client execution timeout."
  name: "cas.spring.cloud.aws.ssm.client-execution-timeout"
  defaultValue: "10000"
- duration: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Connection timeout."
  shortDescription: "Connection timeout."
  name: "cas.spring.cloud.aws.ssm.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  shortDescription: "Use access-key provided by AWS to authenticate."
  name: "cas.spring.cloud.aws.ssm.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  shortDescription: "Use secret key provided by AWS to authenticate."
  name: "cas.spring.cloud.aws.ssm.credential-secret-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  shortDescription: "AWS custom endpoint."
  name: "cas.spring.cloud.aws.ssm.endpoint"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Local address."
  shortDescription: "Local address."
  name: "cas.spring.cloud.aws.ssm.local-address"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  shortDescription: "Maximum connections setting."
  name: "cas.spring.cloud.aws.ssm.max-connections"
  defaultValue: 10
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Profile name to use."
  shortDescription: "Profile name to use."
  name: "cas.spring.cloud.aws.ssm.profile-name"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Profile path."
  shortDescription: "Profile path."
  name: "cas.spring.cloud.aws.ssm.profile-path"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  shortDescription: "Optionally specifies the proxy host to connect through."
  name: "cas.spring.cloud.aws.ssm.proxy-host"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  shortDescription: "Optionally specifies the proxy password to connect through."
  name: "cas.spring.cloud.aws.ssm.proxy-password"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  shortDescription: "Optionally specifies the proxy username to connect through."
  name: "cas.spring.cloud.aws.ssm.proxy-username"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "AWS region used."
  shortDescription: "AWS region used."
  name: "cas.spring.cloud.aws.ssm.region"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  shortDescription: "Outline the requested retry mode."
  name: "cas.spring.cloud.aws.ssm.retry-mode"
  defaultValue: "STANDARD"
- duration: true
  module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.String"
  description: "Socket timeout."
  shortDescription: "Socket timeout."
  name: "cas.spring.cloud.aws.ssm.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-configuration-cloud-aws-ssm"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSystemsManagerParameterStore"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  shortDescription: "Flag that indicates whether to use reaper."
  name: "cas.spring.cloud.aws.ssm.use-reaper"
  defaultValue: false
