---
- method: "GET"
  path: "statistics"
  name: "statistics"
  endpointType: "Endpoint"
  signature: "StatisticsEndpoint.handle()"
  owner: "org.apereo.cas.web.report.StatisticsEndpoint"
  returnType: "Map"
  casEndpoint: true
  summary: "Get a report of CAS statistics."
