---
- method: "POST"
  path: "restart"
  name: "restart"
  endpointType: "Endpoint"
  signature: "RestartEndpoint.restart()"
  owner: "org.springframework.cloud.context.restart.RestartEndpoint"
  returnType: "Object"
  casEndpoint: false
  summary: "Restart the application via a `POST`. Disabled by default."
