logging:
  level:
    root: warn
    org:
      apereo:
        cas: info
casbot:
  github:
    repository:
      organization: apereo
      name: cas
      url: https://github.com/apereo/cas
      committers: mmoayyed,julienhuon,dima767,tsschmidt,leleuj,hdeadman
