---
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.util.List<java.lang.String>"
  description: "Node addresses."
  shortDescription: "Node addresses."
  name: "cas.authn.attribute-repository.couchbase.addresses"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "Bucket name."
  shortDescription: "Bucket name."
  name: "cas.authn.attribute-repository.couchbase.bucket"
  defaultValue: "testbucket"
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "Cluster password."
  shortDescription: "Cluster password."
  name: "cas.authn.attribute-repository.couchbase.cluster-password"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "Cluster username."
  shortDescription: "Cluster username."
  name: "cas.authn.attribute-repository.couchbase.cluster-username"
  defaultValue: ""
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of connection timeout."
  shortDescription: "String representation of connection timeout."
  name: "cas.authn.attribute-repository.couchbase.connection-timeout"
  defaultValue: "PT60S"
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "A value can be assigned to this field to uniquely identify this resolver."
  shortDescription: "A value can be assigned to this field to uniquely identify this\
    \ resolver."
  name: "cas.authn.attribute-repository.couchbase.id"
  defaultValue: ""
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of idle connection timeout."
  shortDescription: "String representation of idle connection timeout."
  name: "cas.authn.attribute-repository.couchbase.idle-connection-timeout"
  defaultValue: "PT60S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of KV timeout."
  shortDescription: "String representation of KV timeout."
  name: "cas.authn.attribute-repository.couchbase.kv-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.Integer"
  description: "Maximum number of connections made to the cluster."
  shortDescription: "Maximum number of connections made to the cluster."
  name: "cas.authn.attribute-repository.couchbase.max-http-connections"
  defaultValue: 5
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.Long"
  description: "Allows to customize the maximum number of requests allowed in the\
    \ retry timer."
  shortDescription: "Allows to customize the maximum number of requests allowed in\
    \ the retry timer."
  name: "cas.authn.attribute-repository.couchbase.max-num-requests-in-retry"
  defaultValue: 32768
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.Integer"
  description: "Maximum number of parallel threads made for queries."
  shortDescription: "Maximum number of parallel threads made for queries."
  name: "cas.authn.attribute-repository.couchbase.max-parallelism"
  defaultValue: 0
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.Integer"
  description: "The order of this attribute repository in the chain of repositories.\
    \ Can be used to explicitly position this source in chain and affects merging\
    \ strategies."
  shortDescription: "The order of this attribute repository in the chain of repositories."
  name: "cas.authn.attribute-repository.couchbase.order"
  defaultValue: 0
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of query threshold."
  shortDescription: "String representation of query threshold."
  name: "cas.authn.attribute-repository.couchbase.query-threshold"
  defaultValue: "PT30S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of query timeout."
  shortDescription: "String representation of query timeout."
  name: "cas.authn.attribute-repository.couchbase.query-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "Query scan consistency. By default, the query engine will return whatever\
    \ is currently in the index at the time of query (this mode is also called {@code\
    \ NOT_BOUNDED}). If you need to include everything that has just been written,\
    \ a different scan consistency must be chosen. If {@code REQUEST_PLUS} is chosen,\
    \ it will likely take a bit longer to return the results but the query engine\
    \ will make sure that it is as up-to-date as possible. Accepted values are: {@code\
    \ NOT_BOUNDED, REQUEST_PLUS}."
  shortDescription: "Query scan consistency."
  name: "cas.authn.attribute-repository.couchbase.scan-consistency"
  defaultValue: "NOT_BOUNDED"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of scan timeout."
  shortDescription: "String representation of scan timeout."
  name: "cas.authn.attribute-repository.couchbase.scan-wait-timeout"
  defaultValue: "PT30S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of search timeout."
  shortDescription: "String representation of search timeout."
  name: "cas.authn.attribute-repository.couchbase.search-timeout"
  defaultValue: "PT30S"
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "Username attribute to fetch attributes by."
  shortDescription: "Username attribute to fetch attributes by."
  name: "cas.authn.attribute-repository.couchbase.username-attribute"
  defaultValue: "username"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbasePrincipalAttributesProperties"
  type: "java.lang.String"
  description: "String representation of view timeout."
  shortDescription: "String representation of view timeout."
  name: "cas.authn.attribute-repository.couchbase.view-timeout"
  defaultValue: "PT30S"
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.util.List<java.lang.String>"
  description: "Node addresses."
  shortDescription: "Node addresses."
  name: "cas.authn.couchbase.addresses"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "Bucket name."
  shortDescription: "Bucket name."
  name: "cas.authn.couchbase.bucket"
  defaultValue: "testbucket"
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "Cluster password."
  shortDescription: "Cluster password."
  name: "cas.authn.couchbase.cluster-password"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "Cluster username."
  shortDescription: "Cluster username."
  name: "cas.authn.couchbase.cluster-username"
  defaultValue: ""
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of connection timeout."
  shortDescription: "String representation of connection timeout."
  name: "cas.authn.couchbase.connection-timeout"
  defaultValue: "PT60S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of idle connection timeout."
  shortDescription: "String representation of idle connection timeout."
  name: "cas.authn.couchbase.idle-connection-timeout"
  defaultValue: "PT60S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of KV timeout."
  shortDescription: "String representation of KV timeout."
  name: "cas.authn.couchbase.kv-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Maximum number of connections made to the cluster."
  shortDescription: "Maximum number of connections made to the cluster."
  name: "cas.authn.couchbase.max-http-connections"
  defaultValue: 5
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.Long"
  description: "Allows to customize the maximum number of requests allowed in the\
    \ retry timer."
  shortDescription: "Allows to customize the maximum number of requests allowed in\
    \ the retry timer."
  name: "cas.authn.couchbase.max-num-requests-in-retry"
  defaultValue: 32768
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Maximum number of parallel threads made for queries."
  shortDescription: "Maximum number of parallel threads made for queries."
  name: "cas.authn.couchbase.max-parallelism"
  defaultValue: 0
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.couchbase.name"
  defaultValue: ""
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Order of authentication handler in chain."
  shortDescription: "Order of authentication handler in chain."
  name: "cas.authn.couchbase.order"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "Password attribute to fetch and compare against credential."
  shortDescription: "Password attribute to fetch and compare against credential."
  name: "cas.authn.couchbase.password-attribute"
  defaultValue: "psw"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of query threshold."
  shortDescription: "String representation of query threshold."
  name: "cas.authn.couchbase.query-threshold"
  defaultValue: "PT30S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of query timeout."
  shortDescription: "String representation of query timeout."
  name: "cas.authn.couchbase.query-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "Query scan consistency. By default, the query engine will return whatever\
    \ is currently in the index at the time of query (this mode is also called {@code\
    \ NOT_BOUNDED}). If you need to include everything that has just been written,\
    \ a different scan consistency must be chosen. If {@code REQUEST_PLUS} is chosen,\
    \ it will likely take a bit longer to return the results but the query engine\
    \ will make sure that it is as up-to-date as possible. Accepted values are: {@code\
    \ NOT_BOUNDED, REQUEST_PLUS}."
  shortDescription: "Query scan consistency."
  name: "cas.authn.couchbase.scan-consistency"
  defaultValue: "NOT_BOUNDED"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of scan timeout."
  shortDescription: "String representation of scan timeout."
  name: "cas.authn.couchbase.scan-wait-timeout"
  defaultValue: "PT30S"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of search timeout."
  shortDescription: "String representation of search timeout."
  name: "cas.authn.couchbase.search-timeout"
  defaultValue: "PT30S"
- required: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "Username attribute to fetch and compare against credential."
  shortDescription: "Username attribute to fetch and compare against credential."
  name: "cas.authn.couchbase.username-attribute"
  defaultValue: "username"
- duration: true
  module: "cas-server-support-couchbase-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchbase.authentication.CouchbaseAuthenticationProperties"
  type: "java.lang.String"
  description: "String representation of view timeout."
  shortDescription: "String representation of view timeout."
  name: "cas.authn.couchbase.view-timeout"
  defaultValue: "PT30S"
