---
- method: "GET"
  path: "status"
  name: "status"
  endpointType: "Endpoint"
  signature: "StatusEndpoint.handle()"
  owner: "org.apereo.cas.web.report.StatusEndpoint"
  returnType: "Map"
  casEndpoint: true
  deprecated: true
  summary: "Provides CAS server's health status."
