---
- duration: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Client execution timeout."
  shortDescription: "Client execution timeout."
  name: "cas.amazon-sts.client-execution-timeout"
  defaultValue: "10000"
- duration: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Connection timeout."
  shortDescription: "Connection timeout."
  name: "cas.amazon-sts.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  shortDescription: "Use access-key provided by AWS to authenticate."
  name: "cas.amazon-sts.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  shortDescription: "Use secret key provided by AWS to authenticate."
  name: "cas.amazon-sts.credential-secret-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  shortDescription: "AWS custom endpoint."
  name: "cas.amazon-sts.endpoint"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Local address."
  shortDescription: "Local address."
  name: "cas.amazon-sts.local-address"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  shortDescription: "Maximum connections setting."
  name: "cas.amazon-sts.max-connections"
  defaultValue: 10
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Attribute name that must be found and resolved for the principal to\
    \ authorize the user to proceed with obtaining credentials."
  shortDescription: "Attribute name that must be found and resolved for the principal\
    \ to authorize the user to proceed with obtaining credentials."
  name: "cas.amazon-sts.principal-attribute-name"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Attribute value, defined as a regex pattern that must be found and\
    \ resolved for the principal to authorize the user to proceed with obtaining credentials."
  shortDescription: "Attribute value, defined as a regex pattern that must be found\
    \ and resolved for the principal to authorize the user to proceed with obtaining\
    \ credentials."
  name: "cas.amazon-sts.principal-attribute-value"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Profile name to use."
  shortDescription: "Profile name to use."
  name: "cas.amazon-sts.profile-name"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Profile path."
  shortDescription: "Profile path."
  name: "cas.amazon-sts.profile-path"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  shortDescription: "Optionally specifies the proxy host to connect through."
  name: "cas.amazon-sts.proxy-host"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  shortDescription: "Optionally specifies the proxy password to connect through."
  name: "cas.amazon-sts.proxy-password"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  shortDescription: "Optionally specifies the proxy username to connect through."
  name: "cas.amazon-sts.proxy-username"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.Boolean"
  description: "When set to {@code true}, credentials will be obtained based on roles\
    \ as attributes resolved for the user. Typically, you could use roles wthin your\
    \ account or for cross-account access. <p> When set to {@code true}, the {@link\
    \ #getPrincipalAttributeName()} must contain {@code roleArn}s as values."
  shortDescription: "When set to {@code true}, credentials will be obtained based\
    \ on roles as attributes resolved for the user."
  name: "cas.amazon-sts.rbac-enabled"
  defaultValue: false
- required: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "AWS region used."
  shortDescription: "AWS region used."
  name: "cas.amazon-sts.region"
  defaultValue: ""
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  shortDescription: "Outline the requested retry mode."
  name: "cas.amazon-sts.retry-mode"
  defaultValue: "STANDARD"
- duration: true
  module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Socket timeout."
  shortDescription: "Socket timeout."
  name: "cas.amazon-sts.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-aws"
  owner: "org.apereo.cas.configuration.model.support.aws.AmazonSecurityTokenServiceProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  shortDescription: "Flag that indicates whether to use reaper."
  name: "cas.amazon-sts.use-reaper"
  defaultValue: false
