---
- module: "cas-server-support-sms-nexmo"
  owner: "org.apereo.cas.configuration.model.support.sms.NexmoProperties"
  type: "java.lang.String"
  description: "Nexmo API secret obtained from Nexmo."
  shortDescription: "Nexmo API secret obtained from Nexmo."
  name: "cas.sms-provider.nexmo.api-secret"
  defaultValue: ""
- required: true
  module: "cas-server-support-sms-nexmo"
  owner: "org.apereo.cas.configuration.model.support.sms.NexmoProperties"
  type: "java.lang.String"
  description: "Nexmo API token obtained from Nexmo."
  shortDescription: "Nexmo API token obtained from Nexmo."
  name: "cas.sms-provider.nexmo.api-token"
  defaultValue: ""
- module: "cas-server-support-sms-nexmo"
  owner: "org.apereo.cas.configuration.model.support.sms.NexmoProperties"
  type: "java.lang.String"
  description: "Nexmo Signature secret obtained from Nexmo."
  shortDescription: "Nexmo Signature secret obtained from Nexmo."
  name: "cas.sms-provider.nexmo.signature-secret"
  defaultValue: ""
