---
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "org.apereo.cas.configuration.model.support.dynamodb.AbstractDynamoDbProperties$BillingMode"
  description: "Billing mode specifies how you are charged for read and write throughput\
    \ and how you manage capacity.\nAvailable values are as follows:\n<ul><li>{@code\
    \ PROVISIONED}: Provisioned mode means that you specify the number of reads\n\
    and writes per second that you expect your\napplication to use.\nProvisioned mode\
    \ is a good option if any of the following are true:\n\n<ul>\n <li>You have predictable\
    \ application traffic.</li>\n <li>You run applications whose traffic is consistent\
    \ or ramps gradually.</li>\n <li>You can forecast capacity requirements to control\
    \ costs.</li>\n</ul>\nYou can use auto scaling to automatically adjust\ncapacity\
    \ based on the specified utilization rate\nto ensure application performance while\
    \ reducing costs.</li><li>{@code PAY_PER_REQUEST}: Pay-per-request or on-demand\
    \ billing means that you're charged for only the read/write\nrequests that you\
    \ use.\nOn-demand mode is a good option if any of the following are true:\n<ul>\n\
    \    <li>You create new tables with unknown workloads.</li>\n    <li>You have\
    \ unpredictable application traffic.</li>\n    <li>You prefer the ease of paying\
    \ for only what you use.</li>\n</ul>\nTables using on-demand mode support all\
    \ DynamoDB\nfeatures (such as encryption at rest, point-in-time recovery, global\n\
    tables, and so on) with the exception of auto scaling,\nwhich is not applicable\
    \ with this mode.</li></ul>"
  shortDescription: "Billing mode specifies how you are charged for read and write\
    \ throughput and how you manage capacity."
  name: "cas.authn.mfa.yubikey.dynamo-db.billing-mode"
  defaultValue: "PROVISIONED"
- duration: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Client execution timeout."
  shortDescription: "Client execution timeout."
  name: "cas.authn.mfa.yubikey.dynamo-db.client-execution-timeout"
  defaultValue: "10000"
- duration: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Connection timeout."
  shortDescription: "Connection timeout."
  name: "cas.authn.mfa.yubikey.dynamo-db.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  shortDescription: "Use access-key provided by AWS to authenticate."
  name: "cas.authn.mfa.yubikey.dynamo-db.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  shortDescription: "Use secret key provided by AWS to authenticate."
  name: "cas.authn.mfa.yubikey.dynamo-db.credential-secret-key"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to drop tables on start up."
  shortDescription: "Flag that indicates whether to drop tables on start up."
  name: "cas.authn.mfa.yubikey.dynamo-db.drop-tables-on-startup"
  defaultValue: false
- required: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  shortDescription: "AWS custom endpoint."
  name: "cas.authn.mfa.yubikey.dynamo-db.endpoint"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Local address."
  shortDescription: "Local address."
  name: "cas.authn.mfa.yubikey.dynamo-db.local-address"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Indicates that the database instance is local to the deployment that\
    \ does not require or use any credentials or other configuration other than host\
    \ and region. This is mostly used during development and testing."
  shortDescription: "Indicates that the database instance is local to the deployment\
    \ that does not require or use any credentials or other configuration other than\
    \ host and region."
  name: "cas.authn.mfa.yubikey.dynamo-db.local-instance"
  defaultValue: false
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  shortDescription: "Maximum connections setting."
  name: "cas.authn.mfa.yubikey.dynamo-db.max-connections"
  defaultValue: 10
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to prevent CAS from creating tables."
  shortDescription: "Flag that indicates whether to prevent CAS from creating tables."
  name: "cas.authn.mfa.yubikey.dynamo-db.prevent-table-creation-on-startup"
  defaultValue: false
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Profile name to use."
  shortDescription: "Profile name to use."
  name: "cas.authn.mfa.yubikey.dynamo-db.profile-name"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Profile path."
  shortDescription: "Profile path."
  name: "cas.authn.mfa.yubikey.dynamo-db.profile-path"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  shortDescription: "Optionally specifies the proxy host to connect through."
  name: "cas.authn.mfa.yubikey.dynamo-db.proxy-host"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  shortDescription: "Optionally specifies the proxy password to connect through."
  name: "cas.authn.mfa.yubikey.dynamo-db.proxy-password"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  shortDescription: "Optionally specifies the proxy username to connect through."
  name: "cas.authn.mfa.yubikey.dynamo-db.proxy-username"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Long"
  description: "Read capacity."
  shortDescription: "Read capacity."
  name: "cas.authn.mfa.yubikey.dynamo-db.read-capacity"
  defaultValue: 10
- required: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "AWS region used."
  shortDescription: "AWS region used."
  name: "cas.authn.mfa.yubikey.dynamo-db.region"
  defaultValue: ""
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  shortDescription: "Outline the requested retry mode."
  name: "cas.authn.mfa.yubikey.dynamo-db.retry-mode"
  defaultValue: "STANDARD"
- duration: true
  module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "Socket timeout."
  shortDescription: "Socket timeout."
  name: "cas.authn.mfa.yubikey.dynamo-db.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.String"
  description: "The table name used and created by CAS to hold devices in DynamoDb."
  shortDescription: "The table name used and created by CAS to hold devices in DynamoDb."
  name: "cas.authn.mfa.yubikey.dynamo-db.table-name"
  defaultValue: "DynamoDbYubiKeyDevices"
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Integer"
  description: "Time offset."
  shortDescription: "Time offset."
  name: "cas.authn.mfa.yubikey.dynamo-db.time-offset"
  defaultValue: 0
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  shortDescription: "Flag that indicates whether to use reaper."
  name: "cas.authn.mfa.yubikey.dynamo-db.use-reaper"
  defaultValue: false
- module: "cas-server-support-yubikey-dynamodb"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyDynamoDbMultifactorProperties"
  type: "java.lang.Long"
  description: "Write capacity."
  shortDescription: "Write capacity."
  name: "cas.authn.mfa.yubikey.dynamo-db.write-capacity"
  defaultValue: 10
