---
- method: "GET"
  path: "beans"
  name: "beans"
  endpointType: "Endpoint"
  signature: "BeansEndpoint.beans()"
  owner: "org.springframework.boot.actuate.beans.BeansEndpoint"
  returnType: "ApplicationBeans"
  casEndpoint: false
  summary: "Displays all CAS application context internal Spring beans."
