---
- module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.InterruptCoreProperties"
  type: "org.apereo.cas.configuration.model.support.interrupt.InterruptCoreProperties$InterruptTriggerModes"
  description: "Define how interrupt notifications should be triggered in the authentication\
    \ flow.\nAvailable values are as follows:\n<ul><li>{@code AFTER_AUTHENTICATION}:\
    \ Trigger interrupt notifications and inquiry\nafter authentication events and\
    \ before\nsingle sign-on has been established.</li><li>{@code AFTER_SSO}: Trigger\
    \ interrupt notifications and inquiry\nafter single sign-on has been established.\n\
    Interrupt queries that execute after single sign-on\ncannot control the creation\
    \ of the\nSSO session conditionally.</li></ul>"
  shortDescription: "Define how interrupt notifications should be triggered in the\
    \ authentication flow."
  name: "cas.interrupt.core.trigger-mode"
  defaultValue: "AFTER_AUTHENTICATION"
- required: true
  module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.GroovyInterruptProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.interrupt.groovy.location"
  defaultValue: ""
- required: true
  module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.JsonInterruptProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.interrupt.json.location"
  defaultValue: ""
- required: true
  module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RegexInterruptProperties"
  type: "java.lang.String"
  description: "A regex pattern on the attribute name that if matches will successfully\
    \ complete the first condition for the interrupt notifications trigger."
  shortDescription: "A regex pattern on the attribute name that if matches will successfully\
    \ complete the first condition for the interrupt notifications trigger."
  name: "cas.interrupt.regex.attribute-name"
  defaultValue: ""
- required: true
  module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RegexInterruptProperties"
  type: "java.lang.String"
  description: "A regex pattern on the attribute value that if matches will successfully\
    \ complete the first condition for the interrupt notifications trigger."
  shortDescription: "A regex pattern on the attribute value that if matches will successfully\
    \ complete the first condition for the interrupt notifications trigger."
  name: "cas.interrupt.regex.attribute-value"
  defaultValue: ""
- module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RestfulInterruptProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  shortDescription: "If REST endpoint is protected via basic authentication, specify\
    \ the password for authentication."
  name: "cas.interrupt.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RestfulInterruptProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  shortDescription: "If REST endpoint is protected via basic authentication, specify\
    \ the username for authentication."
  name: "cas.interrupt.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RestfulInterruptProperties"
  type: "java.util.Map<java.lang.String,java.lang.String>"
  description: "Headers, defined as a Map, to include in the request when making the\
    \ REST call. Will overwrite any header that CAS is pre-defined to send and include\
    \ in the request. Key in the map should be the header name and the value in the\
    \ map should be the header value."
  shortDescription: "Headers, defined as a Map, to include in the request when making\
    \ the REST call."
  name: "cas.interrupt.rest.headers"
  defaultValue: ""
- module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RestfulInterruptProperties"
  type: "java.lang.String"
  description: "HTTP method to use when contacting the rest endpoint. Examples include\
    \ {@code GET, POST}, etc."
  shortDescription: "HTTP method to use when contacting the rest endpoint."
  name: "cas.interrupt.rest.method"
  defaultValue: "GET"
- required: true
  module: "cas-server-support-interrupt-webflow"
  owner: "org.apereo.cas.configuration.model.support.interrupt.RestfulInterruptProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  shortDescription: "The endpoint URL to contact and retrieve attributes."
  name: "cas.interrupt.rest.url"
  defaultValue: ""
