---
- required: true
  module: "cas-server-support-aup-core"
  owner: "org.apereo.cas.configuration.model.support.aup.GroovyAcceptableUsagePolicyProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.acceptable-usage-policy.groovy.location"
  defaultValue: ""
- module: "cas-server-support-aup-core"
  owner: "org.apereo.cas.configuration.model.support.aup.InMemoryAcceptableUsagePolicyProperties"
  type: "org.apereo.cas.configuration.model.support.aup.InMemoryAcceptableUsagePolicyProperties$Scope"
  description: "Scope of map where the aup selection is stored.\nAvailable values\
    \ are as follows:\n<ul><li>{@code GLOBAL}: Store in global in-memory map (for\
    \ life of server).</li><li>{@code AUTHENTICATION}: Store aup acceptance such that\
    \ user is prompted when\nthey authenticate via credentials.</li></ul>"
  shortDescription: "Scope of map where the aup selection is stored."
  name: "cas.acceptable-usage-policy.in-memory.scope"
  defaultValue: "GLOBAL"
