---
- method: "GET"
  path: "resolveAttributes/{uid}"
  name: "resolveAttributes"
  endpointType: "Endpoint"
  signature: "CasResolveAttributesReportEndpoint.resolvePrincipalAttributes(java.lang.String)"
  owner: "org.apereo.cas.web.report.CasResolveAttributesReportEndpoint"
  returnType: "Map"
  casEndpoint: true
  summary: "Resolve principal attributes for user."
  parameters:
  - name: "uid"
    required: true
