---
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.String"
  description: "set API key value for the first API key authentication."
  shortDescription: "set API key value for the first API key authentication."
  name: "cas.sms-provider.text-magic.api-key"
  defaultValue: ""
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.String"
  description: "set API key prefix for the first API key authentication."
  shortDescription: "set API key prefix for the first API key authentication."
  name: "cas.sms-provider.text-magic.api-key-prefix"
  defaultValue: ""
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.Integer"
  description: "connect timeout (in milliseconds)."
  shortDescription: "connect timeout (in milliseconds)."
  name: "cas.sms-provider.text-magic.connect-timeout"
  defaultValue: 5000
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.Boolean"
  description: "Check that whether debugging is enabled for this API client."
  shortDescription: "Check that whether debugging is enabled for this API client."
  name: "cas.sms-provider.text-magic.debugging"
  defaultValue: false
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.String"
  description: "set password for the first HTTP basic authentication."
  shortDescription: "set password for the first HTTP basic authentication."
  name: "cas.sms-provider.text-magic.password"
  defaultValue: ""
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.Integer"
  description: "read timeout (in milliseconds)."
  shortDescription: "read timeout (in milliseconds)."
  name: "cas.sms-provider.text-magic.read-timeout"
  defaultValue: 5000
- required: true
  module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.String"
  description: "Secure token used to establish a handshake."
  shortDescription: "Secure token used to establish a handshake."
  name: "cas.sms-provider.text-magic.token"
  defaultValue: ""
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.String"
  description: "Set the User-Agent header's value (by adding to the default header\
    \ map)."
  shortDescription: "Set the User-Agent header's value (by adding to the default header\
    \ map)."
  name: "cas.sms-provider.text-magic.user-agent"
  defaultValue: ""
- required: true
  module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.String"
  description: "Username authorized to use the service as the bind account."
  shortDescription: "Username authorized to use the service as the bind account."
  name: "cas.sms-provider.text-magic.username"
  defaultValue: ""
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.Boolean"
  description: "Should SSL connections be verified?"
  shortDescription: "Should SSL connections be verified?"
  name: "cas.sms-provider.text-magic.verifying-ssl"
  defaultValue: true
- module: "cas-server-support-sms-textmagic"
  owner: "org.apereo.cas.configuration.model.support.sms.TextMagicProperties"
  type: "java.lang.Integer"
  description: "write timeout (in milliseconds)."
  shortDescription: "write timeout (in milliseconds)."
  name: "cas.sms-provider.text-magic.write-timeout"
  defaultValue: 0
