---
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.FileAuthenticationProperties"
  type: "org.springframework.core.io.Resource"
  description: "File resource where user accounts are kept."
  shortDescription: "File resource where user accounts are kept."
  name: "cas.authn.file.filename"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.FileAuthenticationProperties"
  type: "java.lang.String"
  description: "Authentication handler name used to verify credentials in the file."
  shortDescription: "Authentication handler name used to verify credentials in the\
    \ file."
  name: "cas.authn.file.name"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.FileAuthenticationProperties"
  type: "java.lang.String"
  description: "Separator character that distinguishes between usernames and passwords\
    \ in the file."
  shortDescription: "Separator character that distinguishes between usernames and\
    \ passwords in the file."
  name: "cas.authn.file.separator"
  defaultValue: "::"
- required: true
  module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.GroovyAuthenticationProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.authn.groovy.location"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.GroovyAuthenticationProperties"
  type: "java.lang.String"
  description: "Authentication handler name used to verify credentials in the file."
  shortDescription: "Authentication handler name used to verify credentials in the\
    \ file."
  name: "cas.authn.groovy.name"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.GroovyAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Order of the authentication handler in the chain."
  shortDescription: "Order of the authentication handler in the chain."
  name: "cas.authn.groovy.order"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.GroovyAuthenticationProperties"
  type: "org.apereo.cas.configuration.model.core.authentication.AuthenticationHandlerStates"
  description: "Define the scope and state of this authentication handler and the\
    \ lifecycle in which it can be invoked or activated."
  shortDescription: "Define the scope and state of this authentication handler and\
    \ the lifecycle in which it can be invoked or activated."
  name: "cas.authn.groovy.state"
  defaultValue: ""
- required: true
  module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.JsonResourceAuthenticationProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.authn.json.location"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.JsonResourceAuthenticationProperties"
  type: "java.lang.String"
  description: "Authentication handler name used to verify credentials in the file."
  shortDescription: "Authentication handler name used to verify credentials in the\
    \ file."
  name: "cas.authn.json.name"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.JsonResourceAuthenticationProperties"
  type: "org.apereo.cas.configuration.model.core.authentication.AuthenticationHandlerStates"
  description: "Define the scope and state of this authentication handler and the\
    \ lifecycle in which it can be invoked or activated."
  shortDescription: "Define the scope and state of this authentication handler and\
    \ the lifecycle in which it can be invoked or activated."
  name: "cas.authn.json.state"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.RejectAuthenticationProperties"
  type: "java.lang.String"
  description: "Name of the authentication handler."
  shortDescription: "Name of the authentication handler."
  name: "cas.authn.reject.name"
  defaultValue: ""
- module: "cas-server-support-generic"
  owner: "org.apereo.cas.configuration.model.support.generic.RejectAuthenticationProperties"
  type: "java.lang.String"
  description: "Comma-separated list of users to reject for authentication."
  shortDescription: "Comma-separated list of users to reject for authentication."
  name: "cas.authn.reject.users"
  defaultValue: ""
