---
- module: "cas-server-support-digest-authentication"
  owner: "org.apereo.cas.configuration.model.support.digest.DigestProperties"
  type: "java.lang.String"
  description: "Authentication method used when creating digest header."
  shortDescription: "Authentication method used when creating digest header."
  name: "cas.authn.digest.authentication-method"
  defaultValue: "auth"
- module: "cas-server-support-digest-authentication"
  owner: "org.apereo.cas.configuration.model.support.digest.DigestProperties"
  type: "java.lang.String"
  description: "Name of the authentication handler."
  shortDescription: "Name of the authentication handler."
  name: "cas.authn.digest.name"
  defaultValue: ""
- module: "cas-server-support-digest-authentication"
  owner: "org.apereo.cas.configuration.model.support.digest.DigestProperties"
  type: "java.lang.Integer"
  description: "Order of the authentication handler in the chain."
  shortDescription: "Order of the authentication handler in the chain."
  name: "cas.authn.digest.order"
  defaultValue: ""
- module: "cas-server-support-digest-authentication"
  owner: "org.apereo.cas.configuration.model.support.digest.DigestProperties"
  type: "java.lang.String"
  description: "The digest realm to use."
  shortDescription: "The digest realm to use."
  name: "cas.authn.digest.realm"
  defaultValue: "CAS"
- module: "cas-server-support-digest-authentication"
  owner: "org.apereo.cas.configuration.model.support.digest.DigestProperties"
  type: "java.util.Map<java.lang.String,java.lang.String>"
  description: "Static/stub list of username and passwords to accept if no other account\
    \ store is defined."
  shortDescription: "Static/stub list of username and passwords to accept if no other\
    \ account store is defined."
  name: "cas.authn.digest.users"
  defaultValue: ""
