---
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Base API url used to contact microsoft graph for calls."
  shortDescription: "Base API url used to contact microsoft graph for calls."
  name: "cas.authn.attribute-repository.azure-active-directory[].api-base-url"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Comma-separated attributes and user properties to fetch from microsoft\
    \ graph.\nIf attributes are specified here, they would be the only ones requested\
    \ and fetched.\nIf this field is left blank, a default set of attributes are fetched\
    \ and returned."
  shortDescription: "Comma-separated attributes and user properties to fetch from\
    \ microsoft graph."
  name: "cas.authn.attribute-repository.azure-active-directory[].attributes"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "boolean"
  description: "Whether attribute repository should consider the underlying\nattribute\
    \ names in a case-insensitive manner."
  shortDescription: "Whether attribute repository should consider the underlying attribute\
    \ names in a case-insensitive manner."
  name: "cas.authn.attribute-repository.azure-active-directory[].case-insensitive"
  defaultValue: ""
- required: true
  module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Client id of the registered app in microsoft azure portal."
  shortDescription: "Client id of the registered app in microsoft azure portal."
  name: "cas.authn.attribute-repository.azure-active-directory[].client-id"
  defaultValue: ""
- required: true
  module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Client secret of the registered app in microsoft azure portal."
  shortDescription: "Client secret of the registered app in microsoft azure portal."
  name: "cas.authn.attribute-repository.azure-active-directory[].client-secret"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Domain that is appended to usernames when doing lookups.\nThe {@code\
    \ @} is automatically included."
  shortDescription: "Domain that is appended to usernames when doing lookups."
  name: "cas.authn.attribute-repository.azure-active-directory[].domain"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Grant type used to fetch access tokens; defaults to {@code client_credentials}."
  shortDescription: "Grant type used to fetch access tokens; defaults to {@code client_credentials}."
  name: "cas.authn.attribute-repository.azure-active-directory[].grant-type"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "A value can be assigned to this field to uniquely identify this resolver."
  shortDescription: "A value can be assigned to this field to uniquely identify this\
    \ resolver."
  name: "cas.authn.attribute-repository.azure-active-directory[].id"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Adjust the logging level of the API calls. Defaults to {@code basic}.\n\
    Accepted values are {@code none,headers,basic,body}."
  shortDescription: "Adjust the logging level of the API calls."
  name: "cas.authn.attribute-repository.azure-active-directory[].logging-level"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Base login url used to fetch access tokens."
  shortDescription: "Base login url used to fetch access tokens."
  name: "cas.authn.attribute-repository.azure-active-directory[].login-base-url"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "int"
  description: "The order of this attribute repository in the chain of repositories.\n\
    Can be used to explicitly position this source in chain and affects\nmerging strategies."
  shortDescription: "The order of this attribute repository in the chain of repositories."
  name: "cas.authn.attribute-repository.azure-active-directory[].order"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Resource to fetch access tokens for; defaults to the graph api url."
  shortDescription: "Resource to fetch access tokens for; defaults to the graph api\
    \ url."
  name: "cas.authn.attribute-repository.azure-active-directory[].resource"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "Scope used when fetching access tokens."
  shortDescription: "Scope used when fetching access tokens."
  name: "cas.authn.attribute-repository.azure-active-directory[].scope"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAttributesProperties"
  type: "java.lang.String"
  description: "The microsoft tenant id."
  shortDescription: "The microsoft tenant id."
  name: "cas.authn.attribute-repository.azure-active-directory[].tenant"
  defaultValue: ""
- required: true
  module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "java.lang.String"
  description: "Client id of the application."
  shortDescription: "Client id of the application."
  name: "cas.authn.azure-active-directory.client-id"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "java.lang.String"
  description: "A number of authentication handlers are allowed to determine whether\
    \ they can operate on the provided credential and as such lend themselves to be\
    \ tried and tested during the authentication handler selection phase. The credential\
    \ criteria may be one of the following options:<ul> <li>1) A regular expression\
    \ pattern that is tested against the credential identifier.</li> <li>2) A fully\
    \ qualified class name of your own design that implements {@code Predicate}.</li>\
    \ <li>3) Path to an external Groovy script that implements the same interface.</li>\
    \ </ul>"
  shortDescription: "A number of authentication handlers are allowed to determine\
    \ whether they can operate on the provided credential and as such lend themselves\
    \ to be tried and tested during the authentication handler selection phase."
  name: "cas.authn.azure-active-directory.credential-criteria"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "java.lang.String"
  description: "Login url including the tenant id."
  shortDescription: "Login url including the tenant id."
  name: "cas.authn.azure-active-directory.login-url"
  defaultValue: "https://login.microsoftonline.com/common/"
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.azure-active-directory.name"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "java.lang.Integer"
  description: "The order of this authentication handler in the chain."
  shortDescription: "The order of this authentication handler in the chain."
  name: "cas.authn.azure-active-directory.order"
  defaultValue: ""
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "java.lang.String"
  description: "Resource url for the graph API to fetch attributes."
  shortDescription: "Resource url for the graph API to fetch attributes."
  name: "cas.authn.azure-active-directory.resource"
  defaultValue: "https://graph.microsoft.com/"
- module: "cas-server-support-azuread-authentication"
  owner: "org.apereo.cas.configuration.model.support.azuread.AzureActiveDirectoryAuthenticationProperties"
  type: "org.apereo.cas.configuration.model.core.authentication.AuthenticationHandlerStates"
  description: "Define the scope and state of this authentication handler and the\
    \ lifecycle in which it can be invoked or activated."
  shortDescription: "Define the scope and state of this authentication handler and\
    \ the lifecycle in which it can be invoked or activated."
  name: "cas.authn.azure-active-directory.state"
  defaultValue: ""
