---
- method: "GET"
  path: "info"
  name: "info"
  endpointType: "Endpoint"
  signature: "InfoEndpoint.info()"
  owner: "org.springframework.boot.actuate.info.InfoEndpoint"
  returnType: "Map"
  casEndpoint: false
  summary: "CAS version information and other system traits."
