---
- required: true
  module: "cas-server-support-generic-remote-webflow"
  owner: "org.apereo.cas.configuration.model.support.generic.RemoteAddressAuthenticationProperties"
  type: "java.lang.String"
  description: "The authorized network address to allow for authentication."
  shortDescription: "The authorized network address to allow for authentication."
  name: "cas.authn.remote-address.ip-address-range"
  defaultValue: ""
- module: "cas-server-support-generic-remote-webflow"
  owner: "org.apereo.cas.configuration.model.support.generic.RemoteAddressAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.remote-address.name"
  defaultValue: ""
- module: "cas-server-support-generic-remote-webflow"
  owner: "org.apereo.cas.configuration.model.support.generic.RemoteAddressAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Order of the authentication handler in the chain."
  shortDescription: "Order of the authentication handler in the chain."
  name: "cas.authn.remote-address.order"
  defaultValue: ""
