---
- name: "wsfed.relyingPartyIdentifier"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_WSFED"
  description: "Used when delegating authentication to ADFS to indicate the relying\
    \ party identifier."
- name: "jwtAsServiceTicket"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "JWT_SERVICE_TICKETS"
  description: "Produce a JWT as a response when generating service tickets."
- name: "jwtAsServiceTicketCipherStrategyType"
  defaultValue: "ENCRYPT_AND_SIGN"
  type: "STRING"
  group: "JWT_SERVICE_TICKETS"
  description: "Indicate the cipher strategy for JWT service tickets to determine\
    \ order of signing/encryption operations."
- name: "jwtAsServiceTicketSigningKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_SERVICE_TICKETS"
  description: "Produce a signed JWT as a response when generating service tickets\
    \ using the provided signing key."
- name: "jwtAsServiceTicketEncryptionKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_SERVICE_TICKETS"
  description: "Produce an encrypted JWT as a response when generating service tickets\
    \ using the provided encryption key."
- name: "accessTokenAsJwtSigningKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_ACCESS_TOKENS"
  description: "Produce a signed JWT as a response when generating access tokens using\
    \ the provided signing key."
- name: "accessTokenAsJwtCipherStrategyType"
  defaultValue: "ENCRYPT_AND_SIGN"
  type: "STRING"
  group: "JWT_ACCESS_TOKENS"
  description: "Indicate the cipher strategy for JWTs as access tokens, to determine\
    \ order of signing/encryption operations."
- name: "accessTokenAsJwtSigningEnabled"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "JWT_ACCESS_TOKENS"
  description: "Enable signing JWTs as a response when generating access tokens using\
    \ the provided signing key."
- name: "accessTokenAsJwtEncryptionEnabled"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "JWT_ACCESS_TOKENS"
  description: "Enable encryption of JWTs as a response when generating access tokens\
    \ using the provided encryption key."
- name: "accessTokenAsJwtEncryptionKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_ACCESS_TOKENS"
  description: "Produce an encrypted JWT as a response when generating access tokens\
    \ using the provided encryption key."
- name: "jwtSigningSecret"
  defaultValue: ""
  type: "STRING"
  group: "JWT_AUTHENTICATION"
  description: "Jwt signing secret defined for a given service."
- name: "jwtSigningSecretAlg"
  defaultValue: "HS256"
  type: "STRING"
  group: "JWT_AUTHENTICATION"
  description: "Jwt signing secret alg defined for a given service."
- name: "jwtEncryptionSecret"
  defaultValue: ""
  type: "STRING"
  group: "JWT_AUTHENTICATION"
  description: "Jwt encryption secret defined for a given service."
- name: "jwtEncryptionSecretAlg"
  defaultValue: ""
  type: "STRING"
  group: "JWT_AUTHENTICATION"
  description: "Jwt encryption secret alg defined for a given service."
- name: "jwtEncryptionSecretMethod"
  defaultValue: "A192CBC-HS384"
  type: "STRING"
  group: "JWT_AUTHENTICATION"
  description: "Jwt encryption secret method defined for a given service."
- name: "jwtSecretsAreBase64Encoded"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "JWT_AUTHENTICATION"
  description: "Determine whether secrets are Base64 encoded."
- name: "skipInterrupt"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "INTERRUPTS"
  description: "Whether interrupt notifications should be skipped."
- name: "skipRequiredServiceCheck"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "REGISTERED_SERVICES"
  description: "Whether this service should skip qualification for required-service\
    \ pattern checks."
- name: "httpHeaderEnableCacheControl"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
  description: "Whether CAS should inject cache control headers into the response\
    \ when this service is in process."
- name: "httpHeaderEnableXContentOptions"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
  description: "Whether CAS should inject xcontent options headers into the response\
    \ when this service is in process."
- name: "httpHeaderEnableStrictTransportSecurity"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
  description: "Whether CAS should inject strict transport security headers into the\
    \ response when this service is in process."
- name: "httpHeaderEnableXFrameOptions"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
  description: "Whether CAS should inject xframe options headers into the response\
    \ when this service is in process."
- name: "httpHeaderXFrameOptions"
  defaultValue: "DENY"
  type: "STRING"
  group: "HTTP_HEADERS"
  description: "Whether CAS should override xframe options headers into the response\
    \ when this service is in process."
- name: "httpHeaderEnableContentSecurityPolicy"
  defaultValue: "true"
  type: "STRING"
  group: "HTTP_HEADERS"
  description: "Whether CAS should inject content security policy headers into the\
    \ response when this service is in process."
- name: "httpHeaderEnableXSSProtection"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
  description: "Whether CAS should inject xss protection headers into the response\
    \ when this service is in process."
- name: "corsAllowCredentials"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "CORS"
  description: "Whether CAS should allow credentials in CORS requests."
- name: "corsMaxAge"
  defaultValue: ""
  type: "INTEGER"
  group: "CORS"
  description: "Define the max-age property for CORS requests."
- name: "corsAllowedOrigins"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
  description: "Define allowed origins for CORS requests. Cannot use * when credentials\
    \ are allowed."
- name: "corsAllowedOriginPatterns"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
  description: "Define patterns of allowed origins. (e.g.'https://*.example.com')\
    \ Patterns can be used when credentials are allowed."
- name: "corsAllowedMethods"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
  description: "Define allowed methods for CORS requests. The special value * allows\
    \ all methods."
- name: "corsAllowedHeaders"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
  description: "Define exposed headers in the response for CORS requests. Set the\
    \ list of headers that a pre-flight request can list as allowed for use during\
    \ an actual request. The special value `*` allows actual requests to send any\
    \ header."
- name: "corsExposedHeaders"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
  description: "List of response headers that a response might have and can be exposed.\
    \ The special value `*` allows all headers to be exposed for non-credentialed\
    \ requests."
- name: "forceAuthn"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN"
  description: "Indicate binding type, when using delegated authentication to saml2\
    \ identity providers."
- name: "passiveAuthn"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN"
  description: "Indicate binding type, when using delegated authentication to saml2\
    \ identity providers."
- name: "AuthnRequestBindingType"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate binding type, when using delegated authentication to saml2\
    \ identity providers."
- name: "AssertionConsumerServiceIndex"
  defaultValue: ""
  type: "LONG"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate assertion consumer service index, when using delegated authentication\
    \ to saml2 identity providers."
- name: "AttributeConsumingServiceIndex"
  defaultValue: ""
  type: "LONG"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate attribute consuming service index, when using delegated authentication\
    \ to saml2 identity providers."
- name: "ComparisonType"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate comparison type when using delegated authentication to saml2\
    \ identity providers."
- name: "NameIdPolicyFormat"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate name id policy format, when using delegated authentication\
    \ to saml2 identity providers."
- name: "NameIdPolicyAllowCreate"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate name id policy allow create, when using delegated authentication\
    \ to saml2 identity providers."
- name: "ProviderName"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate provider name, when using delegated authentication to saml2\
    \ identity providers."
- name: "IssuerFormat"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate issuer format, when using delegated authentication to saml2\
    \ identity providers."
- name: "UseNameQualifier"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate whether name qualifier should be used, when using delegated\
    \ authentication to saml2 identity providers."
- name: "AuthnContextClassRefs"
  defaultValue: ""
  type: "SET"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate authn context class refs, when using delegated authentication\
    \ to saml2 identity providers."
- name: "NameIdAttribute"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate the name id attribute when using delegated authentication\
    \ to saml2 identity providers."
- name: "WantsAssertionsSigned"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate whether assertions should be signed, when using delegated\
    \ authentication to saml2 identity providers."
- name: "WantsResponsesSigned"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate whether responses should be signed, when using delegated\
    \ authentication to saml2 identity providers."
- name: "MaximumAuthenticationLifetime"
  defaultValue: ""
  type: "LONG"
  group: "DELEGATED_AUTHN_SAML2"
  description: "Indicate the maximum authentication lifetime to use, when using delegated\
    \ authentication to saml2 identity providers."
- name: "max_age"
  defaultValue: ""
  type: "INTEGER"
  group: "DELEGATED_AUTHN_OIDC"
  description: "Indicate max_age to use, when using delegated authentication to OIDC\
    \ OP"
- name: "scope"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_OIDC"
  description: "Indicate scope to use, when using delegated authentication to OIDC\
    \ OP"
- name: "response_type"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_OIDC"
  description: "Indicate response_type to use, when using delegated authentication\
    \ to OIDC OP"
- name: "response_mode"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_OIDC"
  description: "Indicate response_mode to use, when using delegated authentication\
    \ to OIDC OP"
- name: "scimOAuthToken"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
  description: "Define SCIM OAUTH token"
- name: "scimUsername"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
  description: "Define SCIM username"
- name: "scimPassword"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
  description: "Define SCIM password"
- name: "scimTarget"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
  description: "Define SCIM target"
