---
- module: "cas-server-support-soap-authentication"
  owner: "org.apereo.cas.configuration.model.support.soap.SoapAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.soap.name"
  defaultValue: ""
- module: "cas-server-support-soap-authentication"
  owner: "org.apereo.cas.configuration.model.support.soap.SoapAuthenticationProperties"
  type: "java.lang.Integer"
  description: "The order of this authentication handler in the chain."
  shortDescription: "The order of this authentication handler in the chain."
  name: "cas.authn.soap.order"
  defaultValue: ""
- required: true
  module: "cas-server-support-soap-authentication"
  owner: "org.apereo.cas.configuration.model.support.soap.SoapAuthenticationProperties"
  type: "java.lang.String"
  description: "URL of the SOAP endpoint."
  shortDescription: "URL of the SOAP endpoint."
  name: "cas.authn.soap.url"
  defaultValue: ""
