---
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.Boolean"
  description: "Set whether client lifetime is accepted."
  shortDescription: "Set whether client lifetime is accepted."
  name: "cas.authn.wsfed-idp.sts.conditions-accept-client-lifetime"
  defaultValue: true
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.Boolean"
  description: "If requested lifetime exceeds shall it fail (default) or overwrite\
    \ with maximum lifetime."
  shortDescription: "If requested lifetime exceeds shall it fail (default) or overwrite\
    \ with maximum lifetime."
  name: "cas.authn.wsfed-idp.sts.conditions-fail-lifetime-exceedance"
  defaultValue: false
- duration: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Get how long (in seconds) a client-supplied Created Element is allowed\
    \ to be in the future. The default is 60 seconds to avoid common problems relating\
    \ to clock skew."
  shortDescription: "Get how long (in seconds) a client-supplied Created Element is\
    \ allowed to be in the future."
  name: "cas.authn.wsfed-idp.sts.conditions-future-time-to-live"
  defaultValue: "PT60S"
- duration: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Set the default lifetime in seconds for issued SAML tokens."
  shortDescription: "Set the default lifetime in seconds for issued SAML tokens."
  name: "cas.authn.wsfed-idp.sts.conditions-lifetime"
  defaultValue: "PT30M"
- duration: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Set the maximum lifetime in seconds for issued SAML tokens."
  shortDescription: "Set the maximum lifetime in seconds for issued SAML tokens."
  name: "cas.authn.wsfed-idp.sts.conditions-max-lifetime"
  defaultValue: "PT12H"
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.util.List<java.lang.String>"
  description: "Collection of fully-qualified claims prefixed with the appropriate\
    \ namespace that are expected to be released via attribute release policy."
  shortDescription: "Collection of fully-qualified claims prefixed with the appropriate\
    \ namespace that are expected to be released via attribute release policy."
  name: "cas.authn.wsfed-idp.sts.custom-claims"
  defaultValue: ""
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.Boolean"
  description: "Whether tokens generated by STS should encrypted."
  shortDescription: "Whether tokens generated by STS should encrypted."
  name: "cas.authn.wsfed-idp.sts.encrypt-tokens"
  defaultValue: true
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Keystore path used to encrypt tokens."
  shortDescription: "Keystore path used to encrypt tokens."
  name: "cas.authn.wsfed-idp.sts.encryption-keystore-file"
  defaultValue: ""
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Keystore password used to encrypt tokens."
  shortDescription: "Keystore password used to encrypt tokens."
  name: "cas.authn.wsfed-idp.sts.encryption-keystore-password"
  defaultValue: ""
- required: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceRealmProperties"
  type: "java.lang.String"
  description: "Issuer/name of the realm identified and registered with STS."
  shortDescription: "Issuer/name of the realm identified and registered with STS."
  name: "cas.authn.wsfed-idp.sts.realm.issuer"
  defaultValue: "CAS"
- required: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceRealmProperties"
  type: "java.lang.String"
  description: "Key alias associated with the this realm."
  shortDescription: "Key alias associated with the this realm."
  name: "cas.authn.wsfed-idp.sts.realm.key-password"
  defaultValue: ""
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceRealmProperties"
  type: "java.lang.String"
  description: "Key alias associated with the this realm."
  shortDescription: "Key alias associated with the this realm."
  name: "cas.authn.wsfed-idp.sts.realm.keystore-alias"
  defaultValue: ""
- required: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceRealmProperties"
  type: "java.lang.String"
  description: "Keystore path associated with the this realm."
  shortDescription: "Keystore path associated with the this realm."
  name: "cas.authn.wsfed-idp.sts.realm.keystore-file"
  defaultValue: ""
- required: true
  module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceRealmProperties"
  type: "java.lang.String"
  description: "Keystore password associated with the this realm."
  shortDescription: "Keystore password associated with the this realm."
  name: "cas.authn.wsfed-idp.sts.realm.keystore-password"
  defaultValue: ""
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.Boolean"
  description: "Set whether the provided token will be signed or not. Default is true."
  shortDescription: "Set whether the provided token will be signed or not."
  name: "cas.authn.wsfed-idp.sts.sign-tokens"
  defaultValue: true
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Keystore path used to sign tokens."
  shortDescription: "Keystore path used to sign tokens."
  name: "cas.authn.wsfed-idp.sts.signing-keystore-file"
  defaultValue: ""
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "Keystore password used to sign tokens."
  shortDescription: "Keystore password used to sign tokens."
  name: "cas.authn.wsfed-idp.sts.signing-keystore-password"
  defaultValue: ""
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "When generating a SAML token, indicates the subject name-id format\
    \ to use. Accepted values are: <ul>     <li>unspecified</li>     <li>email</li>\
    \     <li>transient</li>     <li>persistent</li>     <li>entity</li> </ul>"
  shortDescription: "When generating a SAML token, indicates the subject name-id format\
    \ to use."
  name: "cas.authn.wsfed-idp.sts.subject-name-id-format"
  defaultValue: "unspecified"
- module: "cas-server-support-ws-sts"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationSecurityTokenServiceProperties"
  type: "java.lang.String"
  description: "When generating a SAML token, indicates the subject name-id qualifier\
    \ to use."
  shortDescription: "When generating a SAML token, indicates the subject name-id qualifier\
    \ to use."
  name: "cas.authn.wsfed-idp.sts.subject-name-qualifier"
  defaultValue: "http://cxf.apache.org/sts"
