---
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.ntlm.NtlmProperties"
  type: "java.lang.String"
  description: "The domain controller to retrieve if load balanced. Otherwise retrieve\
    \ the domain controller as a possible NT or workgroup."
  shortDescription: "The domain controller to retrieve if load balanced."
  name: "cas.authn.ntlm.domain-controller"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.ntlm.NtlmProperties"
  type: "java.lang.Boolean"
  description: "Whether NTLM authentication should be enabled and registered with\
    \ CAS as well."
  shortDescription: "Whether NTLM authentication should be enabled and registered\
    \ with CAS as well."
  name: "cas.authn.ntlm.enabled"
  defaultValue: false
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.ntlm.NtlmProperties"
  type: "java.lang.String"
  description: "If specified, gets all domain controllers in the specified {@link\
    \ #domainController} and then filters hosts that match the pattern."
  shortDescription: "If specified, gets all domain controllers in the specified {@link\
    \ #domainController} and then filters hosts that match the pattern."
  name: "cas.authn.ntlm.include-pattern"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.ntlm.NtlmProperties"
  type: "java.lang.Boolean"
  description: "Indicates how the domain controller should be retrieved, whether matched\
    \ and filtered by a pattern or retrieved as possible NT or workgroup."
  shortDescription: "Indicates how the domain controller should be retrieved, whether\
    \ matched and filtered by a pattern or retrieved as possible NT or workgroup."
  name: "cas.authn.ntlm.load-balance"
  defaultValue: true
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.ntlm.NtlmProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.ntlm.name"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.ntlm.NtlmProperties"
  type: "java.lang.Integer"
  description: "The order of the authentication handler in the chain."
  shortDescription: "The order of the authentication handler in the chain."
  name: "cas.authn.ntlm.order"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "long"
  description: "Jcifs Netbios cache policy."
  shortDescription: "Jcifs Netbios cache policy."
  name: "cas.authn.spnego.properties[].cache-policy"
  defaultValue: "600"
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs domain."
  shortDescription: "The Jcifs domain."
  name: "cas.authn.spnego.properties[].jcifs-domain"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs domain controller."
  shortDescription: "The Jcifs domain controller."
  name: "cas.authn.spnego.properties[].jcifs-domain-controller"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs netbios wins."
  shortDescription: "The Jcifs netbios wins."
  name: "cas.authn.spnego.properties[].jcifs-netbios-wins"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs password."
  shortDescription: "The Jcifs password."
  name: "cas.authn.spnego.properties[].jcifs-password"
  defaultValue: ""
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs service password."
  shortDescription: "The Jcifs service password."
  name: "cas.authn.spnego.properties[].jcifs-service-password"
  defaultValue: ""
- required: true
  module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs service principal."
  shortDescription: "The Jcifs service principal."
  name: "cas.authn.spnego.properties[].jcifs-service-principal"
  defaultValue: "HTTP/cas.example.com@EXAMPLE.COM"
- module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "The Jcifs username."
  shortDescription: "The Jcifs username."
  name: "cas.authn.spnego.properties[].jcifs-username"
  defaultValue: ""
- duration: true
  module: "cas-server-support-spnego"
  owner: "org.apereo.cas.configuration.model.support.spnego.SpnegoAuthenticationProperties"
  type: "java.lang.String"
  description: "Spnego JCIFS timeout."
  shortDescription: "Spnego JCIFS timeout."
  name: "cas.authn.spnego.properties[].timeout"
  defaultValue: "PT5M"
