---
- method: "POST"
  path: "shutdown"
  name: "shutdown"
  endpointType: "Endpoint"
  signature: "ShutdownEndpoint.shutdown()"
  owner: "org.springframework.boot.actuate.context.ShutdownEndpoint"
  returnType: "Map"
  casEndpoint: false
  summary: "Shut down the application via a `POST`. Disabled by default."
