---
- module: "cas-server-support-configuration-cloud-jdbc"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.Jdbc"
  type: "java.lang.String"
  description: "Driver class name."
  shortDescription: "Driver class name."
  name: "cas.spring.cloud.jdbc.driver-class"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-jdbc"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.Jdbc"
  type: "java.lang.String"
  description: "Database password."
  shortDescription: "Database password."
  name: "cas.spring.cloud.jdbc.password"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-jdbc"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.Jdbc"
  type: "java.lang.String"
  description: "SQL statement."
  shortDescription: "SQL statement."
  name: "cas.spring.cloud.jdbc.sql"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-jdbc"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.Jdbc"
  type: "java.lang.String"
  description: "Database url."
  shortDescription: "Database url."
  name: "cas.spring.cloud.jdbc.url"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-jdbc"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.Jdbc"
  type: "java.lang.String"
  description: "Database user."
  shortDescription: "Database user."
  name: "cas.spring.cloud.jdbc.user"
  defaultValue: ""
