---
- module: "cas-server-core"
  owner: "org.apereo.cas.configuration.model.core.CasJavaClientProperties"
  type: "java.lang.String"
  description: "Prefix of the CAS server used to establish ticket validators for the\
    \ client. Typically set to {@code https://sso.example.org/cas}"
  shortDescription: "Prefix of the CAS server used to establish ticket validators\
    \ for the client."
  name: "cas.client.prefix"
  defaultValue: ""
- module: "cas-server-core"
  owner: "org.apereo.cas.configuration.model.core.CasJavaClientProperties"
  type: "org.apereo.cas.configuration.model.core.CasJavaClientProperties$ClientTicketValidatorTypes"
  description: "Determines the type of ticket validator that CAS should create from\
    \ the Java CAS client when attempting to issue in-bound ticket validation calls.\n\
    Available values are as follows:\n<ul><li>{@code CAS10}: CAS10 ticket validator.</li><li>{@code\
    \ CAS20}: CAS20 ticket validator.</li><li>{@code CAS30}: CAS30 ticket validator.</li><li>{@code\
    \ JSON}: JSON ticket validator.</li></ul>"
  shortDescription: "Determines the type of ticket validator that CAS should create\
    \ from the Java CAS client when attempting to issue in-bound ticket validation\
    \ calls."
  name: "cas.client.validator-type"
  defaultValue: "CAS30"
- module: "cas-server-core"
  owner: "org.apereo.cas.configuration.model.core.CasServerHostProperties"
  type: "java.lang.String"
  description: "Name of the networking host configured to run CAS server. A CAS host\
    \ is automatically appended to the ticket ids generated by CAS. If none is specified,\
    \ one is automatically detected and used by CAS."
  shortDescription: "Name of the networking host configured to run CAS server."
  name: "cas.host.name"
  defaultValue: ""
- required: true
  module: "cas-server-core"
  owner: "org.apereo.cas.configuration.model.core.CasServerProperties"
  type: "java.lang.String"
  description: "Full name of the CAS server. This is the public-facing address of\
    \ the CAS deployment and not the individual node address, in the event that CAS\
    \ is clustered."
  shortDescription: "Full name of the CAS server."
  name: "cas.server.name"
  defaultValue: "https://cas.example.org:8443"
- expressionLanguage: true
  required: true
  module: "cas-server-core"
  owner: "org.apereo.cas.configuration.model.core.CasServerProperties"
  type: "java.lang.String"
  description: "A concatenation of the server name plus the CAS context path. Deployments\
    \ at root likely need to blank out this value."
  shortDescription: "A concatenation of the server name plus the CAS context path."
  name: "cas.server.prefix"
  defaultValue: "/cas"
- expressionLanguage: true
  required: true
  module: "cas-server-core"
  owner: "org.apereo.cas.configuration.model.core.CasServerProperties"
  type: "java.lang.String"
  description: "The CAS Server scope."
  shortDescription: "The CAS Server scope."
  name: "cas.server.scope"
  defaultValue: "example.org"
