---
- module: "cas-server-support-audit-rest"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditRestProperties"
  type: "java.lang.Boolean"
  description: "Make storage requests asynchronously."
  shortDescription: "Make storage requests asynchronously."
  name: "cas.audit.rest.asynchronous"
  defaultValue: true
- module: "cas-server-support-audit-rest"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditRestProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  shortDescription: "If REST endpoint is protected via basic authentication, specify\
    \ the password for authentication."
  name: "cas.audit.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-audit-rest"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditRestProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  shortDescription: "If REST endpoint is protected via basic authentication, specify\
    \ the username for authentication."
  name: "cas.audit.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-audit-rest"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditRestProperties"
  type: "java.util.Map<java.lang.String,java.lang.String>"
  description: "Headers, defined as a Map, to include in the request when making the\
    \ REST call. Will overwrite any header that CAS is pre-defined to send and include\
    \ in the request. Key in the map should be the header name and the value in the\
    \ map should be the header value."
  shortDescription: "Headers, defined as a Map, to include in the request when making\
    \ the REST call."
  name: "cas.audit.rest.headers"
  defaultValue: ""
- module: "cas-server-support-audit-rest"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditRestProperties"
  type: "java.lang.String"
  description: "HTTP method to use when contacting the rest endpoint. Examples include\
    \ {@code GET, POST}, etc."
  shortDescription: "HTTP method to use when contacting the rest endpoint."
  name: "cas.audit.rest.method"
  defaultValue: "GET"
- required: true
  module: "cas-server-support-audit-rest"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditRestProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  shortDescription: "The endpoint URL to contact and retrieve attributes."
  name: "cas.audit.rest.url"
  defaultValue: ""
