---
- name: "/src/main/resources/templates/acceptto/casAccepttoRegistrationView.html"
- name: "/src/main/resources/templates/adaptive-authn/casRiskAuthenticationBlockedView.html"
- name: "/src/main/resources/templates/admin/casAdminLoginView.html"
- name: "/src/main/resources/templates/aup/casAcceptableUsagePolicyView.html"
- name: "/src/main/resources/templates/authy/casAuthyLoginView.html"
- name: "/src/main/resources/templates/consent/casConsentView.html"
- name: "/src/main/resources/templates/delegated-authn/casDelegatedAuthnErrorView.html"
- name: "/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html"
- name: "/src/main/resources/templates/duo-security/casDuoLoginView.html"
- name: "/src/main/resources/templates/error.html"
- name: "/src/main/resources/templates/error/401.html"
- name: "/src/main/resources/templates/error/403.html"
- name: "/src/main/resources/templates/error/404.html"
- name: "/src/main/resources/templates/error/405.html"
- name: "/src/main/resources/templates/error/423.html"
- name: "/src/main/resources/templates/error/casServiceErrorView.html"
- name: "/src/main/resources/templates/forgot-username/casForgotUsernameSendInfoView.html"
- name: "/src/main/resources/templates/forgot-username/casForgotUsernameSentInfoView.html"
- name: "/src/main/resources/templates/fragments/accepttoQRCode.html"
- name: "/src/main/resources/templates/fragments/footer.html"
- name: "/src/main/resources/templates/fragments/header.html"
- name: "/src/main/resources/templates/fragments/loginProviders.html"
- name: "/src/main/resources/templates/fragments/loginform.html"
- name: "/src/main/resources/templates/fragments/loginsidebar.html"
- name: "/src/main/resources/templates/fragments/material.html"
- name: "/src/main/resources/templates/fragments/pmlinks.html"
- name: "/src/main/resources/templates/fragments/pwdupdateform.html"
- name: "/src/main/resources/templates/fragments/qrAuthentication.html"
- name: "/src/main/resources/templates/fragments/recaptcha.html"
- name: "/src/main/resources/templates/fragments/scripts.html"
- name: "/src/main/resources/templates/fragments/serviceui.html"
- name: "/src/main/resources/templates/fragments/submitbutton.html"
- name: "/src/main/resources/templates/fragments/webAuthnLogin.html"
- name: "/src/main/resources/templates/gauth/casGoogleAuthenticatorConfirmRegistrationView.html"
- name: "/src/main/resources/templates/gauth/casGoogleAuthenticatorLoginView.html"
- name: "/src/main/resources/templates/gauth/casGoogleAuthenticatorRegistrationView.html"
- name: "/src/main/resources/templates/gua/casGuaDisplayUserGraphicsView.html"
- name: "/src/main/resources/templates/gua/casGuaGetUserIdView.html"
- name: "/src/main/resources/templates/interrupt/casInterruptView.html"
- name: "/src/main/resources/templates/inwebo/casInweboBrowserAuthnView.html"
- name: "/src/main/resources/templates/inwebo/casInweboCheckResultView.html"
- name: "/src/main/resources/templates/inwebo/casInweboErrorView.html"
- name: "/src/main/resources/templates/inwebo/casInweboSelectAuthnView.html"
- name: "/src/main/resources/templates/layout.html"
- name: "/src/main/resources/templates/login-error/casAccountDisabledView.html"
- name: "/src/main/resources/templates/login-error/casAccountLockedView.html"
- name: "/src/main/resources/templates/login-error/casAuthenticationBlockedView.html"
- name: "/src/main/resources/templates/login-error/casBadHoursView.html"
- name: "/src/main/resources/templates/login-error/casBadWorkstationView.html"
- name: "/src/main/resources/templates/login-error/casExpiredPassView.html"
- name: "/src/main/resources/templates/login-error/casMustChangePassView.html"
- name: "/src/main/resources/templates/login/casConfirmView.html"
- name: "/src/main/resources/templates/login/casGenericSuccessView.html"
- name: "/src/main/resources/templates/login/casLoginMessageView.html"
- name: "/src/main/resources/templates/login/casLoginView.html"
- name: "/src/main/resources/templates/logout/casConfirmLogoutView.html"
- name: "/src/main/resources/templates/logout/casLogoutView.html"
- name: "/src/main/resources/templates/logout/casPropagateLogoutView.html"
- name: "/src/main/resources/templates/mfa-trusted-devices/casMfaRegisterDeviceView.html"
- name: "/src/main/resources/templates/mfa/casCompositeMfaProviderSelectionView.html"
- name: "/src/main/resources/templates/mfa/casMfaDeniedView.html"
- name: "/src/main/resources/templates/mfa/casMfaUnavailableView.html"
- name: "/src/main/resources/templates/password-reset/casPasswordUpdateSuccessView.html"
- name: "/src/main/resources/templates/password-reset/casResetPasswordErrorView.html"
- name: "/src/main/resources/templates/password-reset/casResetPasswordSendInstructionsView.html"
- name: "/src/main/resources/templates/password-reset/casResetPasswordSentInstructionsView.html"
- name: "/src/main/resources/templates/password-reset/casResetPasswordVerifyQuestionsView.html"
- name: "/src/main/resources/templates/passwordless/casPasswordlessDisplayView.html"
- name: "/src/main/resources/templates/passwordless/casPasswordlessGetUserIdView.html"
- name: "/src/main/resources/templates/protocol/2.0/casProxyFailureView.html"
- name: "/src/main/resources/templates/protocol/2.0/casProxySuccessView.html"
- name: "/src/main/resources/templates/protocol/2.0/casServiceValidationFailure.html"
- name: "/src/main/resources/templates/protocol/2.0/casServiceValidationSuccess.html"
- name: "/src/main/resources/templates/protocol/3.0/casServiceValidationFailure.html"
- name: "/src/main/resources/templates/protocol/3.0/casServiceValidationSuccess.html"
- name: "/src/main/resources/templates/protocol/casPostResponseView.html"
- name: "/src/main/resources/templates/protocol/oauth/confirm.html"
- name: "/src/main/resources/templates/protocol/oauth/deviceCodeApproval.html"
- name: "/src/main/resources/templates/protocol/oauth/deviceCodeApproved.html"
- name: "/src/main/resources/templates/protocol/oauth/sessionStaleMismatchError.html"
- name: "/src/main/resources/templates/protocol/oidc/confirm.html"
- name: "/src/main/resources/templates/protocol/openid/casOpenIdAssociationSuccessView.html"
- name: "/src/main/resources/templates/protocol/openid/casOpenIdServiceFailureView.html"
- name: "/src/main/resources/templates/protocol/openid/casOpenIdServiceSuccessView.html"
- name: "/src/main/resources/templates/protocol/openid/user.html"
- name: "/src/main/resources/templates/radius/casRadiusLoginView.html"
- name: "/src/main/resources/templates/saml2-discovery/casSamlIdPDiscoveryView.html"
- name: "/src/main/resources/templates/simple-mfa/casSimpleMfaLoginView.html"
- name: "/src/main/resources/templates/storage/casSessionStorageReadView.html"
- name: "/src/main/resources/templates/storage/casSessionStorageWriteView.html"
- name: "/src/main/resources/templates/surrogate/casSurrogateAuthnListView.html"
- name: "/src/main/resources/templates/swivel/casSwivelLoginView.html"
- name: "/src/main/resources/templates/u2f/casU2fLoginView.html"
- name: "/src/main/resources/templates/u2f/casU2fRegistrationView.html"
- name: "/src/main/resources/templates/webauthn/casWebAuthnLoginView.html"
- name: "/src/main/resources/templates/webauthn/casWebAuthnRegistrationView.html"
- name: "/src/main/resources/templates/wsfed/casWsFedStopWebflow.html"
- name: "/src/main/resources/templates/yubikey/casYubiKeyLoginView.html"
- name: "/src/main/resources/templates/yubikey/casYubiKeyRegistrationView.html"
