---
- module: "cas-server-support-saml-googleapps"
  owner: "org.apereo.cas.configuration.model.support.saml.googleapps.GoogleAppsProperties"
  type: "java.lang.String"
  description: "Signature algorithm used to generate keys. @deprecated Since 6.2"
  shortDescription: "Signature algorithm used to generate keys."
  name: "cas.google-apps.key-algorithm"
  defaultValue: "RSA"
  deprecationLevel: "ERROR"
- module: "cas-server-support-saml-googleapps"
  owner: "org.apereo.cas.configuration.model.support.saml.googleapps.GoogleAppsProperties"
  type: "java.lang.String"
  description: "The private key location that is used to sign responses, etc. @deprecated\
    \ Since 6.2"
  shortDescription: "The private key location that is used to sign responses, etc."
  name: "cas.google-apps.private-key-location"
  defaultValue: "file:/etc/cas/private.key"
  deprecationLevel: "ERROR"
- module: "cas-server-support-saml-googleapps"
  owner: "org.apereo.cas.configuration.model.support.saml.googleapps.GoogleAppsProperties"
  type: "java.lang.String"
  description: "The public key location that is also shared with google apps. @deprecated\
    \ Since 6.2"
  shortDescription: "The public key location that is also shared with google apps."
  name: "cas.google-apps.public-key-location"
  defaultValue: "file:/etc/cas/public.key"
  deprecationLevel: "ERROR"
