---
- duration: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Client execution timeout."
  shortDescription: "Client execution timeout."
  name: "cas.authn.cloud-directory.client-execution-timeout"
  defaultValue: "10000"
- duration: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Connection timeout."
  shortDescription: "Connection timeout."
  name: "cas.authn.cloud-directory.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  shortDescription: "Use access-key provided by AWS to authenticate."
  name: "cas.authn.cloud-directory.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  shortDescription: "Use secret key provided by AWS to authenticate."
  name: "cas.authn.cloud-directory.credential-secret-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Directory ARN."
  shortDescription: "Directory ARN."
  name: "cas.authn.cloud-directory.directory-arn"
  defaultValue: ""
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  shortDescription: "AWS custom endpoint."
  name: "cas.authn.cloud-directory.endpoint"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Facet name."
  shortDescription: "Facet name."
  name: "cas.authn.cloud-directory.facet-name"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Local address."
  shortDescription: "Local address."
  name: "cas.authn.cloud-directory.local-address"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  shortDescription: "Maximum connections setting."
  name: "cas.authn.cloud-directory.max-connections"
  defaultValue: 10
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.cloud-directory.name"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.Integer"
  description: "The order of this authentication handler in the chain."
  shortDescription: "The order of this authentication handler in the chain."
  name: "cas.authn.cloud-directory.order"
  defaultValue: ""
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Password attribute to choose on the entry to compare."
  shortDescription: "Password attribute to choose on the entry to compare."
  name: "cas.authn.cloud-directory.password-attribute-name"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Profile name to use."
  shortDescription: "Profile name to use."
  name: "cas.authn.cloud-directory.profile-name"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Profile path."
  shortDescription: "Profile path."
  name: "cas.authn.cloud-directory.profile-path"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  shortDescription: "Optionally specifies the proxy host to connect through."
  name: "cas.authn.cloud-directory.proxy-host"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  shortDescription: "Optionally specifies the proxy password to connect through."
  name: "cas.authn.cloud-directory.proxy-password"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  shortDescription: "Optionally specifies the proxy username to connect through."
  name: "cas.authn.cloud-directory.proxy-username"
  defaultValue: ""
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "AWS region used."
  shortDescription: "AWS region used."
  name: "cas.authn.cloud-directory.region"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  shortDescription: "Outline the requested retry mode."
  name: "cas.authn.cloud-directory.retry-mode"
  defaultValue: "STANDARD"
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Schema ARN."
  shortDescription: "Schema ARN."
  name: "cas.authn.cloud-directory.schema-arn"
  defaultValue: ""
- duration: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Socket timeout."
  shortDescription: "Socket timeout."
  name: "cas.authn.cloud-directory.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  shortDescription: "Flag that indicates whether to use reaper."
  name: "cas.authn.cloud-directory.use-reaper"
  defaultValue: false
- required: true
  module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Username attribute to choose when locating accounts."
  shortDescription: "Username attribute to choose when locating accounts."
  name: "cas.authn.cloud-directory.username-attribute-name"
  defaultValue: ""
- module: "cas-server-support-cloud-directory-authentication"
  owner: "org.apereo.cas.configuration.model.support.clouddirectory.AmazonCloudDirectoryProperties"
  type: "java.lang.String"
  description: "Username index path."
  shortDescription: "Username index path."
  name: "cas.authn.cloud-directory.username-index-path"
  defaultValue: ""
