---
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Integer"
  description: "Length of the generated code."
  shortDescription: "Length of the generated code."
  name: "cas.authn.mfa.gauth.core.code-digits"
  defaultValue: 6
- required: true
  module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "Issuer used in the barcode when dealing with device registration events.\
    \ Used in the registration URL to identify CAS."
  shortDescription: "Issuer used in the barcode when dealing with device registration\
    \ events."
  name: "cas.authn.mfa.gauth.core.issuer"
  defaultValue: "CASIssuer"
- required: true
  module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "Label used in the barcode when dealing with device registration events.\
    \ Used in the registration URL to identify CAS."
  shortDescription: "Label used in the barcode when dealing with device registration\
    \ events."
  name: "cas.authn.mfa.gauth.core.label"
  defaultValue: "CASLabel"
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Boolean"
  description: "When enabled, allows the user/system to accept multiple accounts and\
    \ device registrations per user, allowing one to switch between or register new\
    \ devices/accounts automatically."
  shortDescription: "When enabled, allows the user/system to accept multiple accounts\
    \ and device registrations per user, allowing one to switch between or register\
    \ new devices/accounts automatically."
  name: "cas.authn.mfa.gauth.core.multiple-device-registration-enabled"
  defaultValue: false
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Long"
  description: "The expiration time of the generated code in seconds."
  shortDescription: "The expiration time of the generated code in seconds."
  name: "cas.authn.mfa.gauth.core.time-step-size"
  defaultValue: 30
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Indicates whether this provider should support trusted devices."
  shortDescription: "Indicates whether this provider should support trusted devices."
  name: "cas.authn.mfa.gauth.core.trusted-device-enabled"
  defaultValue: false
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.CoreGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Integer"
  description: "Since TOTP passwords are time-based, it is essential that the clock\
    \ of both the server and the client are synchronised within the tolerance defined\
    \ here as the window size."
  shortDescription: "Since TOTP passwords are time-based, it is essential that the\
    \ clock of both the server and the client are synchronised within the tolerance\
    \ defined here as the window size."
  name: "cas.authn.mfa.gauth.core.window-size"
  defaultValue: 3
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.GoogleAuthenticatorMultifactorProperties"
  type: "org.apereo.cas.configuration.model.support.mfa.BaseMultifactorAuthenticationProviderProperties$MultifactorAuthenticationProviderFailureModes"
  description: "The failure mode policy for this MFA provider. The authentication\
    \ policy by default supports fail-closed mode, which means that if you attempt\
    \ to exercise a particular provider available to CAS and the provider cannot be\
    \ reached, authentication will be stopped and an error will be displayed. You\
    \ can of course change this behavior so that authentication proceeds without exercising\
    \ the provider functionality, if that provider cannot respond. Each defined multifactor\
    \ authentication provider can set its own failure mode policy. Failure modes set\
    \ at this location will override the global failure mode, but defer to any failure\
    \ mode set by the registered service.\nAvailable values are as follows:\n<ul><li>{@code\
    \ OPEN}: Disallow MFA, proceed with authentication but don't communicate MFA to\
    \ the RP.</li><li>{@code CLOSED}: Disallow MFA, block with authentication.</li><li>{@code\
    \ PHANTOM}: Disallow MFA, proceed with authentication and communicate MFA to the\
    \ RP.</li><li>{@code NONE}: Do not check for failure at all.</li><li>{@code UNDEFINED}:\
    \ The default one indicating that no failure mode is set at all.</li></ul>"
  shortDescription: "The failure mode policy for this MFA provider."
  name: "cas.authn.mfa.gauth.failure-mode"
  defaultValue: "CLOSED"
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.GoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "The identifier for the multifactor provider. In most cases, this need\
    \ not be configured explicitly, unless multiple instances of the same provider\
    \ type are configured in CAS."
  shortDescription: "The identifier for the multifactor provider."
  name: "cas.authn.mfa.gauth.id"
  defaultValue: ""
- required: true
  module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.JsonGoogleAuthenticatorMultifactorProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.authn.mfa.gauth.json.location"
  defaultValue: ""
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.GoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler used to verify credentials\
    \ in MFA."
  shortDescription: "The name of the authentication handler used to verify credentials\
    \ in MFA."
  name: "cas.authn.mfa.gauth.name"
  defaultValue: ""
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.GoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Integer"
  description: "The order of the authentication handler in the chain."
  shortDescription: "The order of the authentication handler in the chain."
  name: "cas.authn.mfa.gauth.order"
  defaultValue: ""
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.GoogleAuthenticatorMultifactorProperties"
  type: "java.lang.Integer"
  description: "At times, CAS needs to determine the correct provider when step-up\
    \ authentication is required. Consider for a moment that CAS already has established\
    \ an SSO session with/without a provider and has reached a level of authentication.\
    \ Another incoming request attempts to exercise that SSO session with a different\
    \ and often competing authentication requirement that may differ from the authentication\
    \ level CAS has already established. Concretely, examples may be: <ul> <li>CAS\
    \ has achieved an SSO session, but a separate request now requires step-up authentication\
    \ with DuoSecurity.</li> <li>CAS has achieved an SSO session with an authentication\
    \ level satisfied by DuoSecurity, but a separate request now requires step-up\
    \ authentication with YubiKey. </li> </ul> In certain scenarios, CAS will attempt\
    \ to rank authentication levels and compare them with each other. If CAS already\
    \ has achieved a level that is higher than what the incoming request requires,\
    \ no step-up authentication will be performed. If the opposite is true, CAS will\
    \ route the authentication flow to the required authentication level and upon\
    \ success, will adjust the SSO session with the new higher authentication level\
    \ now satisfied. Ranking of authentication methods is done per provider via specific\
    \ properties for each. Note that the higher the rank value is, the higher on the\
    \ security scale it remains. A provider that ranks higher with a larger weight\
    \ value trumps and override others with a lower value."
  shortDescription: "At times, CAS needs to determine the correct provider when step-up\
    \ authentication is required."
  name: "cas.authn.mfa.gauth.rank"
  defaultValue: 0
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  shortDescription: "If REST endpoint is protected via basic authentication, specify\
    \ the password for authentication."
  name: "cas.authn.mfa.gauth.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  shortDescription: "If REST endpoint is protected via basic authentication, specify\
    \ the username for authentication."
  name: "cas.authn.mfa.gauth.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.util.Map<java.lang.String,java.lang.String>"
  description: "Headers, defined as a Map, to include in the request when making the\
    \ REST call. Will overwrite any header that CAS is pre-defined to send and include\
    \ in the request. Key in the map should be the header name and the value in the\
    \ map should be the header value."
  shortDescription: "Headers, defined as a Map, to include in the request when making\
    \ the REST call."
  name: "cas.authn.mfa.gauth.rest.headers"
  defaultValue: ""
- required: true
  module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "Endpoint url of the REST resource used for tokens that are kept to\
    \ prevent replay attacks."
  shortDescription: "Endpoint url of the REST resource used for tokens that are kept\
    \ to prevent replay attacks."
  name: "cas.authn.mfa.gauth.rest.token-url"
  defaultValue: ""
- required: true
  module: "cas-server-support-gauth"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  shortDescription: "The endpoint URL to contact and retrieve attributes."
  name: "cas.authn.mfa.gauth.rest.url"
  defaultValue: ""
