---
- required: true
  module: "cas-server-support-sms-twilio"
  owner: "org.apereo.cas.configuration.model.support.sms.TwilioProperties"
  type: "java.lang.String"
  description: "Twilio account identifier used for authentication."
  shortDescription: "Twilio account identifier used for authentication."
  name: "cas.sms-provider.twilio.account-id"
  defaultValue: ""
- required: true
  module: "cas-server-support-sms-twilio"
  owner: "org.apereo.cas.configuration.model.support.sms.TwilioProperties"
  type: "java.lang.String"
  description: "Twilio secret token used for authentication."
  shortDescription: "Twilio secret token used for authentication."
  name: "cas.sms-provider.twilio.token"
  defaultValue: ""
