---
- module: "cas-server-support-saml"
  owner: "org.apereo.cas.configuration.model.support.saml.SamlCoreProperties"
  type: "java.lang.String"
  description: "Attribute namespace to use when generating SAML1 responses."
  shortDescription: "Attribute namespace to use when generating SAML1 responses."
  name: "cas.saml-core.attribute-namespace"
  defaultValue: "http://www.ja-sig.org/products/cas/"
- module: "cas-server-support-saml"
  owner: "org.apereo.cas.configuration.model.support.saml.SamlCoreProperties"
  type: "java.lang.Integer"
  description: "Issue length that controls the validity period of the assertion."
  shortDescription: "Issue length that controls the validity period of the assertion."
  name: "cas.saml-core.issue-length"
  defaultValue: 30
- module: "cas-server-support-saml"
  owner: "org.apereo.cas.configuration.model.support.saml.SamlCoreProperties"
  type: "java.lang.String"
  description: "Issuer of the assertion when generating SAML1 responses."
  shortDescription: "Issuer of the assertion when generating SAML1 responses."
  name: "cas.saml-core.issuer"
  defaultValue: "localhost"
- module: "cas-server-support-saml"
  owner: "org.apereo.cas.configuration.model.support.saml.SamlCoreProperties"
  type: "java.lang.String"
  description: "Qualified name of the security manager class used for creating a SAML\
    \ parser pool."
  shortDescription: "Qualified name of the security manager class used for creating\
    \ a SAML parser pool."
  name: "cas.saml-core.security-manager"
  defaultValue: "org.apache.xerces.util.SecurityManager"
- duration: true
  module: "cas-server-support-saml"
  owner: "org.apereo.cas.configuration.model.support.saml.SamlCoreProperties"
  type: "java.lang.String"
  description: "Skew allowance that controls the issue instance of the authentication."
  shortDescription: "Skew allowance that controls the issue instance of the authentication."
  name: "cas.saml-core.skew-allowance"
  defaultValue: "PT30S"
- module: "cas-server-support-saml"
  owner: "org.apereo.cas.configuration.model.support.saml.SamlCoreProperties"
  type: "java.lang.Boolean"
  description: "Whether ticket ids generated should be saml2 compliant when generating\
    \ SAML1 responses."
  shortDescription: "Whether ticket ids generated should be saml2 compliant when generating\
    \ SAML1 responses."
  name: "cas.saml-core.ticketid-saml2"
  defaultValue: false
