---
- module: "cas-server-support-themes"
  owner: "org.apereo.cas.configuration.model.support.themes.ThemeProperties"
  type: "java.lang.String"
  description: "The default theme name of this CAS deployment."
  shortDescription: "The default theme name of this CAS deployment."
  name: "cas.theme.default-theme-name"
  defaultValue: "cas-theme-default"
- module: "cas-server-support-themes"
  owner: "org.apereo.cas.configuration.model.support.themes.ThemeProperties"
  type: "java.lang.String"
  description: "The parameter name used to switch themes."
  shortDescription: "The parameter name used to switch themes."
  name: "cas.theme.param-name"
  defaultValue: "theme"
