---
- name: "cas.standard.css.file"
  value: "/css/cas.css"
  description: "Path to theme CSS file; `/themes/[theme_name]/css/cas.css`. Multiple\
    \ files may be comma-separated."
- name: "cas.standard.js.file"
  value: "/js/cas.js"
  description: "Path to theme Javascript file; `/themes/[theme_name]/js/js/css` Multiple\
    \ files may be comma-separated."
- name: "cas.logo.file"
  value: ""
  description: "Path to theme logo to display via the common layout. Example: /images/logo.png"
- name: "cas.drawer-menu.enabled"
  value: "true"
  description: "Decide whether drawer menu should be displayed."
- name: "cas.theme.name"
  value: "Default"
  description: "The name of this theme used in various titles/captions."
- name: "cas.pm-links.enabled"
  value: "true"
  description: "Whether password management/reset links should be displayed."
- name: "cas.login-form.enabled"
  value: "true"
  description: "When the CAS login form should be displayed."
- name: "cas.notifications-menu.enabled"
  value: "true"
  description: "Enable and display the notifications menu."
- name: "cas.favicon.file"
  value: ""
  description: "Path to the theme favicon Example: `/themes/example/images/favicon.ico`"
- name: "cas.theme.description"
  value: "Central"
  description: ""
- name: "cas.hero-banner.file"
  value: ""
  description: "Path to a \"hero\" styled image/logo that would be displayed on the\
    \ login form."
- name: "cas.js.core.enabled"
  value: "true"
  description: "Whether core/default Javascript libraries should be included in the\
    \ theme."
